# From https://joeshaw.org/smaller-docker-containers-for-go-apps/

FROM golang:1.7.1

ARG endpoint
ENV ENDPOINT $endpoint

RUN go get github.com/Envoke-org/envoke-api
COPY / Dockerfile.run

CMD tar -cf - -C / Dockerfile.run -C $GOPATH/bin envoke-api

