FROM golang:1.7.1

ADD Makefile /
WORKDIR /

RUN go get -tags netgo -installsuffix netgo github.com/Envoke-org/envoke-api
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./go/src/github.com/Envoke-org/envoke-api

CMD ["/bin/bash"]